export const TW_SPACING = [
	{ level: 0, px: 0 },
	{ level: "px", px: 1 },
	{ level: 0.5, px: 2 },
	{ level: 1, px: 4 },
	{ level: 1.5, px: 6 },
	{ level: 2, px: 8 },
	{ level: 2.5, px: 10 },
	{ level: 3, px: 12 },
	{ level: 3.5, px: 14 },
	{ level: 4, px: 16 },
	{ level: 5, px: 20 },
	{ level: 6, px: 24 },
	{ level: 7, px: 28 },
	{ level: 8, px: 32 },
	{ level: 9, px: 36 },
	{ level: 10, px: 40 },
	{ level: 11, px: 44 },
	{ level: 12, px: 48 },
	{ level: 14, px: 56 },
	{ level: 16, px: 64 },
	{ level: 20, px: 80 },
	{ level: 24, px: 96 },
	{ level: 28, px: 112 },
	{ level: 32, px: 128 },
	{ level: 36, px: 144 },
	{ level: 40, px: 160 },
	{ level: 44, px: 176 },
	{ level: 48, px: 192 },
	{ level: 52, px: 208 },
	{ level: 56, px: 224 },
	{ level: 60, px: 240 },
	{ level: 64, px: 256 },
	{ level: 72, px: 288 },
	{ level: 80, px: 320 },
	{ level: 96, px: 384 },
];

export const TW_FONT_SIZES = [
	{ cls: "text-xs", px: 12 },
	{ cls: "text-sm", px: 14 },
	{ cls: "text-base", px: 16 },
	{ cls: "text-lg", px: 18 },
	{ cls: "text-xl", px: 20 },
	{ cls: "text-2xl", px: 24 },
	{ cls: "text-3xl", px: 30 },
	{ cls: "text-4xl", px: 36 },
	{ cls: "text-5xl", px: 48 },
	{ cls: "text-6xl", px: 60 },
	{ cls: "text-7xl", px: 72 },
	{ cls: "text-8xl", px: 96 },
	{ cls: "text-9xl", px: 128 },
];

export const TW_FONT_WEIGHTS = [
	{ cls: "font-thin", val: 100 },
	{ cls: "font-extralight", val: 200 },
	{ cls: "font-light", val: 300 },
	{ cls: "font-normal", val: 400 },
	{ cls: "font-medium", val: 500 },
	{ cls: "font-semibold", val: 600 },
	{ cls: "font-bold", val: 700 },
	{ cls: "font-extrabold", val: 800 },
	{ cls: "font-black", val: 900 },
];

export const TAILWIND_MAPPED = new Set([
	"display",
	"position",
	"flex-direction",
	"flex-wrap",
	"align-items",
	"justify-content",
	"gap",
	"padding-top",
	"padding-right",
	"padding-bottom",
	"padding-left",
	"margin-top",
	"margin-right",
	"margin-bottom",
	"margin-left",
	"width",
	"height",
	"min-width",
	"min-height",
	"max-width",
	"max-height",
	"text-align",
	"font-size",
	"font-weight",
	"border-radius",
	"border",
	"border-color",
	"border-style",
	"border-top-width",
	"border-right-width",
	"border-bottom-width",
	"border-left-width",
	"overflow",
	"cursor",
	"opacity",
	"box-shadow",
	"white-space",
	"text-decoration",
	"text-transform",
	"visibility",
	"z-index",
	"object-fit",
	"outline",
	"color",
	"background-color",
	"line-height",
	"font-family",
	"letter-spacing",
	"flex",
	"top",
	"right",
	"bottom",
	"left",
	"aspect-ratio",
	"background-size",
]);
